# Generated by Django 5.0.1 on 2024-01-08 22:55

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('icon', models.ImageField(blank=True, default='category/default_image.jpg', null=True, upload_to='categories/icon-image/%Y/%m/%d/', verbose_name='Category Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, default='posts/default_image.jpg', null=True, upload_to='posts/post-image/%Y/%m/%d/', verbose_name='Post Image')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
