# Generated by Django 4.2.9 on 2024-01-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/post_default.png', null=True, upload_to='blog/post-img/%Y/%m/%d/', verbose_name='Post Image'),
        ),
    ]
