# Generated by Django 4.2.9 on 2024-01-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/img/profile_default.webp', null=True, upload_to='profile/%Y/%m/%d/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
