# Generated by Django 4.2.9 on 2024-01-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_usermodel_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%Y/%m/%d/', verbose_name='Profile Picture'),
        ),
    ]
